server.port=${PORT:8080}


management.endpoints.web.exposure.include=health
management.endpoints.health.exposure.include=all ways
management.endpoint.health.probes.enabled=true
management.health.default.enabled=true
# H2 Database
spring.datasource.url=jdbc:h2:file:/temp/:taskmanagerdb;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=taskManagerSecretKey2024VeryLongSecretKeyForJWTSigning
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:3000,https://*.railway.app,https://*.up.railway.app
